baseURL = "https://simpleriscv.com"
title = "Simple RISC-V"
copyright = "Copyright © 2020, Simple RISC-V; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-158044636-1"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Simple RISC-V Authors"
  description = "Building the future with RISC-V"
#  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  [params.social]
    rss = true
    email = "contact@simpleriscv.com"
#    facebook = "https://facebook.com"
    twitter = "https://twitter.com/simpleriscv"
#    linkedin = "https://linkedin.com"
#    stack-overflow = "https://stackoverflow.com"
#    instagram = "https://stackoverflow.com"
    github = "https://github.com/theandrew168/simpleriscv"
#    weibo = "https://www.weibo.com"
#    medium = "https://medium.com"
#    pinterest = "https://pinterest.com"
#    reddit = "https://reddit.com"
#    gitlab = "https://gitlab.com"
#    mastodon = "https://mastodon.social"
#    keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
